import { Button } from "@/components/ui/button";
import { Download, Loader2 } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import { useState } from "react";

interface PdfExportButtonProps {
  reportData: any;
  documentName: string;
}

export const PdfExportButton = ({ reportData, documentName }: PdfExportButtonProps) => {
  const [isExporting, setIsExporting] = useState(false);
  const { toast } = useToast();

  const exportToPdf = async () => {
    setIsExporting(true);
    try {
      // Create HTML content for PDF
      const htmlContent = `
        <!DOCTYPE html>
        <html>
        <head>
          <meta charset="UTF-8">
          <title>Compliance Report - ${documentName}</title>
          <style>
            body { font-family: Arial, sans-serif; margin: 40px; color: #333; }
            h1 { color: #2563eb; border-bottom: 3px solid #2563eb; padding-bottom: 10px; }
            h2 { color: #1e40af; margin-top: 30px; }
            .header { margin-bottom: 30px; }
            .metadata { background: #f1f5f9; padding: 15px; border-radius: 8px; margin-bottom: 30px; }
            .metadata-item { margin: 5px 0; }
            .risk-badge { display: inline-block; padding: 4px 12px; border-radius: 4px; font-weight: bold; font-size: 14px; }
            .risk-critical { background: #dc2626; color: white; }
            .risk-high { background: #f97316; color: white; }
            .risk-medium { background: #eab308; color: white; }
            .risk-low { background: #22c55e; color: white; }
            .issue { background: #fef2f2; border-left: 4px solid #dc2626; padding: 15px; margin: 15px 0; border-radius: 4px; }
            .issue-title { font-weight: bold; color: #991b1b; margin-bottom: 8px; }
            .recommendation { background: #f0fdf4; border-left: 4px solid #22c55e; padding: 15px; margin: 15px 0; border-radius: 4px; }
            .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #e2e8f0; text-align: center; color: #64748b; font-size: 12px; }
          </style>
        </head>
        <body>
          <div class="header">
            <h1>Compliance Analysis Report</h1>
            <p><strong>Document:</strong> ${documentName}</p>
            <p><strong>Generated:</strong> ${new Date().toLocaleString()}</p>
          </div>

          <div class="metadata">
            <div class="metadata-item">
              <strong>Compliance Score:</strong> ${reportData.compliance_score}/100
            </div>
            <div class="metadata-item">
              <strong>Risk Level:</strong> <span class="risk-badge risk-${reportData.risk_level.toLowerCase()}">${reportData.risk_level}</span>
            </div>
            <div class="metadata-item">
              <strong>Issues Detected:</strong> ${reportData.issues_detected?.length || 0}
            </div>
          </div>

          <h2>Executive Summary</h2>
          <p>${reportData.analysis_summary || 'No summary available.'}</p>

          <h2>Issues Detected</h2>
          ${reportData.issues_detected?.map((issue: any) => `
            <div class="issue">
              <div class="issue-title">${issue.title}</div>
              <p><strong>Severity:</strong> ${issue.severity}</p>
              <p><strong>Category:</strong> ${issue.category}</p>
              <p>${issue.description}</p>
              <p><strong>Recommendation:</strong> ${issue.recommendation}</p>
              <p><strong>Timeline:</strong> ${issue.timeline}</p>
            </div>
          `).join('') || '<p>No issues detected.</p>'}

          <h2>Recommendations</h2>
          ${reportData.recommendations?.map((rec: any) => `
            <div class="recommendation">
              <p><strong>Priority:</strong> ${rec.priority} | <strong>Timeline:</strong> ${rec.timeline}</p>
              <p>${rec.action}</p>
            </div>
          `).join('') || '<p>No recommendations available.</p>'}

          <div class="footer">
            <p>This report was generated by Risk & Compliance Advisor AI</p>
            <p>© ${new Date().getFullYear()} - Confidential</p>
          </div>
        </body>
        </html>
      `;

      // Create a Blob and download
      const blob = new Blob([htmlContent], { type: 'text/html' });
      const url = URL.createObjectURL(blob);
      
      // For now, we'll download as HTML. In production, you'd use a PDF generation service
      const link = document.createElement('a');
      link.href = url;
      link.download = `compliance-report-${documentName}-${Date.now()}.html`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);

      toast({
        title: "Success",
        description: "Report exported successfully",
      });
    } catch (error) {
      console.error('Export failed:', error);
      toast({
        title: "Error",
        description: "Failed to export report",
        variant: "destructive"
      });
    } finally {
      setIsExporting(false);
    }
  };

  return (
    <Button onClick={exportToPdf} disabled={isExporting} variant="outline">
      {isExporting ? (
        <>
          <Loader2 className="h-4 w-4 mr-2 animate-spin" />
          Exporting...
        </>
      ) : (
        <>
          <Download className="h-4 w-4 mr-2" />
          Export PDF
        </>
      )}
    </Button>
  );
};
