export interface UserActivityLog {
  log_id?: number; // Optional: Will be generated by the database
  user_id: string; // UUID of the user performing the action
  action_type: 'upload' | 'download' | 'analyze' | 'delete' | 'login' | 'logout'; // Type of action
  document_id?: string; // Optional: Related document ID
  details?: Record<string, any>; // Optional: JSONB for additional details
  timestamp?: string; // Optional: Will be generated by the database
}

export interface Document {
  doc_id: string;
  user_id: string;
  title: string;
  source: string;
  date: string | null;
  domain: string;
  risk_type: string;
  severity: string;
  compliance_score: number;
  summary: string;
  embedding: string; // JSON string of a number[]
  created_at: string;
  tags: string[];
  download_link: string;
  review_required: boolean;
}
