// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://csxgbbergsrbrvdnejdw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNzeGdiYmVyZ3NyYnJ2ZG5lamR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0NDk5NDIsImV4cCI6MjA3MTAyNTk0Mn0.LEwvF9JEpLwMY1UHyYqsXlLCPpgWb3Vr3BAx3cXkdGE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});